baseURL = "https://ernestsong.com"
disqusShortname = ""
enableRobotsTXT = true
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Bigspring Hugo"
[markup.goldmark.renderer]
unsafe = true
