[[main]]
name = "Home"
url = "https://ernestsong.netlify.app/"
weight = "1"
[[main]]
name = "Approach"
url = "#approach"
weight = "2"
[[main]]
name = "Projects"
url = "#projects"
weight = "3"
[[main]]
name = "Clients"
url = "#clients"
weight = "4"
[[main]]
name = "Contact"
url = "contact"
weight = "5"

# footer menu left
[[footer_left]]
name = "Brussels, Belgium"
icon = "fas fa-home"
url = "#"

[[footer_left]]
name = "ernest.song@gmail.com"
icon = "far fa-envelope"
url = "#"

[[footer_left]]
name = "+(32) 476 60 05 90"
icon = "fas fa-phone"
url = "#"

# footer menu middle
[[footer_middle]]
name = ""
url = "#"

# footer menu right
[[footer_right]]
name = ""
url = "#"