[[main]]
name = "Home"
url = "https://ernestsong.com/"
weight = "1"
[[main]]
name = "Approach"
url = "#approach"
weight = "2"
[[main]]
name = "Projects"
url = "#projects"
weight = "3"
[[main]]
name = "Clients"
url = "#clients"
weight = "4"

# footer menu left
[[footer_left]]
name = "Brussels, Belgium"
url = "#"

[[footer_left]]
name = "ernest.song@gmail.com"
url = "#"

[[footer_left]]
name = "+(32) 476 60 05 90"
url = "#"

[[footer_left]]
name = "VAT BE0766.646.824"
url = "#"
