footer_left = []
footer_middle = []
footer_right = []
[[main]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/ernestsong/"
weight = ""
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Contact"
url = "contact"
weight = 4
