author = "Ernest Song"
contact_form_action = "#"
description = "Ernest is Finance Executive Advisor specialized in Finance modeling and Business controlling."
logo = "images/logo.png"
favicon = "images/favicon.png"
logo_width = "250px"
[navigation_button]
enable = true
label = "Contact Us"
link = "contact"
[preloader]
enable = false
preloader = ""

# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

############################# social site ########################
[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/ernestsong/"
