author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
logo = "images/logo.png"
logo_width = "200px"
[navigation_button]
enable = true
label = "Get Started"
link = "contact"
[preloader]
enable = false
preloader = ""
[[social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/ernestsong/"
title = "linkedin"
