author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
logo = "images/logo.png"
logo_width = "250px"
social = []
[navigation_button]
enable = true
label = "Contact Us"
link = "contact"
[preloader]
enable = false
preloader = ""

############################# social site ########################
[[social]]
title = "linkedin"
icon = "fab fa-linkedin"
link = "#"